version: '3'

services:
  keycloak:
    image: jboss/keycloak:latest
    command:
      - "-b"
      - "172.17.132.56"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      - KEYCLOAK_USER=keycloak
      - KEYCLOAK_PASSWORD=keycloak
      - DB_VENDOR=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_ADDR=172.17.132.56
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
    ports:
      - "8000:8080"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloakdb
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: