version: '3'

services:
  keycloak:
    image: jboss/keycloak:latest
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - DB_VENDOR=${DB_VENDOR}
      - DB_USER=${POSTGRESQL_USER}
      - DB_PASSWORD=${POSTGRESQL_PASSWORD}
      - DB_ADDR=${DB_ADDR}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${POSTGRESQL_DATABASE}
    ports:
      - "8000:8080"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: